drop database if exists loja;
create database loja;
use loja;
create table produtos (id integer auto_increment primary key, nome varchar(255), preco decimal(10,2));
insert into produtos (nome, preco) values ('Carro', 20000);
insert into produtos (nome, preco) values ('Motocicleta', 10000);
insert into produtos (nome, preco) values ('Bicicleta', 300);
alter table produtos add column descricao text;
update produtos set descricao = 'Descrição deste produto.';
create table categorias (id integer auto_increment primary key, nome varchar(255));
insert into categorias (nome) values ('esporte'), ('escolar'), ('mobilidade');
alter table produtos add column categoria_id integer;
update produtos set categoria_id = 3;
alter table produtos add column usado boolean default false;
create table usuarios (id integer auto_increment primary key, email varchar(255), senha varchar(255));
insert into usuarios (email,senha) values ('rcksander@gmail.com', '9106689bdeb64ab47a9449a4719ab236');
ALTER TABLE produtos ADD COLUMN isbn VARCHAR(255);
ALTER TABLE produtos ADD COLUMN tipoProduto VARCHAR(255);
ALTER TABLE produtos ADD COLUMN waterMark VARCHAR(255);
ALTER TABLE produtos ADD COLUMN taxaImpressao VARCHAR(255);